project:
  type: website
  output-dir: docs

website:
  page-footer:
    left: ""
    right:
      - icon: github
        href: https://github.com/moreilly23

  title: "Miles' Website"
  navbar:
    left:
      - text: "Home"
      - file: index.qmd
      - portfolio.qmd
      - VA Analysis.qmd
      - text: "Resume"
      - href: https://drive.google.com/file/d/1zAVPlym0UHgr4pgYzyK2647T5wwYe7Bf/view?usp=sharing


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



