project:
  type: website
  output-dir: docs

website:
  page-footer:
    left: ""
    right:
      - icon: github
        href: https://github.com/moreilly23

  title: "Miles O'Reilly"
  navbar:
    left:
      - text: "Home"
      - file: index.qmd
      - portfolio.qmd
      - VA Analysis.qmd
      - walkie.qmd
      - text: Resume
      - href: https://docs.google.com/document/d/1ndvGhaL2B1C4ve2Np-jA_cEQ4p_WGg4McJgkXW6RI2Y/edit?usp=sharing
    right:
      - icon: linkedin
        href: www.linkedin.com/in/milesoreilly

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


editor: visual



