---
title: "VA Analysis"
editor: visual
---

title: "Virginia Election Project" author: "Miles O'Reilly" execute: echo: true format: html: self-contained: true code-tools: true ---

```{r setup, include=FALSE, warning=FALSE, message=FALSE}
#This will be a walkthrough of my analysis of both Virginia's 2020 presidential election and 2021 gubernatorial election data. We will start of by librarying the packages we will use.

library(tidyverse)
library(janitor)
library(httr)
library(jsonlite)
library(kableExtra)
library(here)
library(DT)
options(scipen = 999)
options(stringsAsFactors = FALSE)


```

# Comparing Virgnia Gov vs. Prez

```{r}
#Using the DT package, we will transform the Virginia voting data csv file into a more digestible paginated table through the 'datatable' function. 

joined_vacomparison <- read.csv("joined_vacomparison.csv") 

DT::datatable(joined_vacomparison)
```

```{r}
#Although the table displays a lot of information on each candidate's success, it does not show any direct comparisons among them. Using tidyverse's 'mutate()' function, I will form and new data column that will demonstrate the margin between Youngkin's and Trump's percentage. Positive values demonstrate that Youngkin performed better in a specific county than Trump while negatives indicate that he performed weaker in the same locality. 

Rmargin= mutate(joined_vacomparison, YoungkinMarg= pct_youngkin-trump_pct) 
DT::datatable(Rmargin)

#Using the 'head()' function, I will trim the data to only show Youngkin's top five counties in terms of his margin with Trump. 

Top5 <- arrange(Rmargin, desc(YoungkinMarg)) 
Top5county <- head(Top5,5) 
DT::datatable(Top5county)

#Finally, after focusing in on the specific data points we want, I will use ggplot's charting function to visualize Youngkin's best performances in a bar chart. This chart was created through the use of 'reorder()', in which I graphed his margin in respect to localities. 

ggplot(Top5county, aes(x=reorder(locality, YoungkinMarg), y=YoungkinMarg)) + geom_bar(stat = "identity", color = "black", fill = "red") + coord_flip() +
  labs(title="Youngkin's Top Five Counties vs. Trump", x="County", y="Margin Percentage")
  

```

```{r}
# After seeing where Youngkin outperformed Trump, I want to see the counties in which he personally saw the most success. This data only represents the counties where he received the highest percentage of votes and is not related to how Trump or any other candidate performed previously. Using the same process as with the margin section, I first apply 'mutate()' to form a new column, trim the top 5 through'head()', and then visualize the findings through ggplots 'geom_bar'. 

YoungkinSenate <- arrange(joined_vacomparison, desc(pct_youngkin)) 
Youngkin5 <- head(YoungkinSenate, 5) 
DT::datatable(Youngkin5)

ggplot(Youngkin5, aes(x=reorder(locality, pct_youngkin), y=pct_youngkin)) + geom_bar(stat = "identity", color = "black", fill = "blue") + coord_flip() +
  labs(title="Youngkin's Top Five Counties", x="County", y="Percentage of Vote")

```

```{r}

#Now let's look at Youngkin's Democratic opponent, McAullife. First we will mutate the datatable and isolate his top 5 counties. We will then display his success in these counties through a DT 'datatable()' function. I will then use 'visible=FALSE' with all columns except pct_mcauliffe to remove data that does not pertain to exactly what we want, which is the percentage he won. 

McCauliffe <- arrange(joined_vacomparison, desc(pct_mcauliffe))
MC5 <- head(McCauliffe, 5) 
DT::datatable(MC5)
datatable(MC5, options=list(columnDefs = list(list(visible=FALSE, targets=c(2,3,4,5,6,7, 8)))))


```

```{r}
#The first of my personal findings relates to the presidential election. I was curious to see where Biden outperformed Trump and to what extent his margin of victory was. Using the same process as before, I trimmed his election data and displayed the top 5 in a datatable. Using the same 'visible=FALSE' code, I removed all columns about the gubernatorial election from the table to make it easier to see data that only relates to Trump vs. Biden.  

PresElec= mutate(joined_vacomparison, BidenMarg = biden_pct-trump_pct) 
Biden5 <- arrange(PresElec, desc(BidenMarg)) 
Biden5county <- head(Biden5, 5) 
DT::datatable(Biden5county)
datatable(Biden5county, options=list(columnDefs = list(list(visible=FALSE, targets=c(6,7,8,9)))))


```

```{r}
#My second finding continues with the presidential election but is on Trump rather than Biden. While I previously calculated Biden's highest victory margins, for this section I wanted to graph pure Trump support. A similar process to calculating margins, this time however I focused purely on number of votes received and then graphed this through ggplot's geom_bar, using the 'reorder()' function. 

trumpnumbers <- arrange(joined_vacomparison, desc(trump))
trump5 <- head(trumpnumbers, 5) 
ggplot(trump5, aes(x=reorder(locality, trump), y=trump)) + geom_bar(stat = "identity", color = "white", fill = "red") +
  coord_flip()+
    labs(title="Trump's Top 5 Counties", x="County", y="Number of Votes")

```

```{r}

#My final finding pertains to the division, or if there was any, within the Democratic camp. I wanted to see if McAuliffe received less support in the same counties than Biden did so I used 'mutate()' to calculate the percentage margin. I then isolated the 5 counties with the highest margin and displayed them in a ggplot bar chart. The negative values indicate the counties where McAuliffe received less vote percentage than Biden did in his election. 

Dmargin <- mutate(joined_vacomparison, MCmarg= pct_mcauliffe-biden_pct) 
Dmargincounty <- arrange(Dmargin, desc(MCmarg)) 
Dmargin5 <- head(Dmargincounty, 5) 

DT::datatable(Dmargin5)

ggplot(Dmargin5, aes(x=reorder(locality, MCmarg), y=MCmarg)) +   
geom_bar(stat = "identity", color = "black", fill = "blue") +   
coord_flip() +
    labs(title="Where Did McAuliffe Lose The Most 2020 (D) Votes?", x="County", y="Percentage Loss")

```

------------------------------------------------------------------------
